# Generated by Django 5.2.7 on 2025-10-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_appointment_app', '0002_appointment_endtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='endtime',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
